learning_log/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
    path('users/', include('users.urls')),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'

urlpatterns = [
    path('', views.index,name = 'index'),
    path('topics/', views.topics,name = 'topics'),
    path('topics/<int:topic_id>/', views.topic,name = 'topic'),
    path('new_topic/', views.new_topic,name = 'new_topic'),
    path('new_entry/<topic_id>/', views.new_entry,name = 'new_entry'),
    path('edit_entry/<entry_id>/', views.edit_entry,name = 'edit_entry'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import login
from . import views

app_name = 'users'

urlpatterns = [
    path('login/',login,{'template_name':'users/login.html'},name = 'login'),
    path('logout/',views.logout_view,name = 'logout'),
    # path('register/',views.register,name = 'register'),
    path('signup/',views.signup,name = "signup"),

]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User,on_delete = models.CASCADE)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic,on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        return self.text[:100]+'... ... ...'

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 100,'rows':10})}

    

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required


from .models import Topic,Entry
from .forms import TopicForm,EntryForm

def index(request):
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner = request.user)
    context = {'topics':topics,}
    return render(request,'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
    topic = Topic.objects.get(id = topic_id)
    if topic.owner != request.user:
        raise Http404('Please add entry to see them.')

    entries = topic.entry_set.all()
    context = {'topic':topic,'entries':entries,}
    return render(request,'learning_logs/topic.html',context)

@login_required
def new_topic(request):
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():

            # text = form.cleaned_data['text']
            # Topic.objects.create(
            #     text = text
            # ).save()
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()

            
            return HttpResponseRedirect('/topics/')
    else:
        form = TopicForm()

    context = {'form':form,}
    return render(request,'learning_logs/new_topic.html',context)
    
@login_required   
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    
    if request.method == 'POST':
        # No data submitted; create a blank form.
         
        # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic_id]))      
    else:
        form = EntryForm() 
    
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context) 

@login_required
def edit_entry(request,entry_id):
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404('Please add entry to see them.')

    if request.method == 'POST':
        form = EntryForm(instance=entry,data = request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args = [topic.id]))

    else:
        form = EntryForm(instance=entry) 

    context = {'entry':entry,'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context) 

        



    

users/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))


# def register(request):
#     if request.method == 'POST':
#         form = UserCreationForm(data = request.POST)
#         if form.is_valid():
#             new_user = form.save()
#             user = authenticate(username = new_user.username,
#             password = request.POST['password1'])
#             login(request,user)
#             return HttpResponseRedirect(reverse('learning_logs:index'))

#     else:
#         form = UserCreationForm()
    
#     context = {'form':form,}
#     return render(request,'users/register.html',context)


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username = username, password = password)
            login(request, user)
            return redirect('/')
    else:
            form = UserCreationForm()
            
    return render(request,'registration/signup.html',{'form':form})

learning_logs/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {% load static %}
    <!--css from bootswatch  -->
     <link rel="stylesheet" href={% static 'learning_logs/css/cyborg.css' %}> 

    <!--CDN ba BOOTSWATCH je kono ekta use korte hobe-->

    <!--CDN css-->

    <!-- 
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
    s-->
    
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
    
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>

    <!--My style-->
    <link rel="stylesheet" href="{% static 'learning_logs/css/style.css' %}" > 

    <!--favicon-->
    <link rel="shortcut icon" href="{%  static 'learning_logs/img/L1.png' %}">

    <title>Learning Log</title>
    

</head>
<body>
     <br> 
    
     <nav class="navbar navbar-dark bg-dark fixed-top navbar-expand-md ">
        <div class="container">
            <a href="{% url 'learning_logs:index' %}">
                <img src="{% static 'learning_logs/img/ll.ico' %}" width="40" height="40" class="mr-2">
            </a>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            <button class="navbar-toggler  navbar-toggler-right" data-toggle = "collapse" data-target = "#display">
                <span class="navbar-toggler-icon"></span>
            </button>               
            <div id="display" class="collapse navbar-collapse">
                <ul class="navbar-nav active ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>                                
                    </li>
                        
                    {% if user.is_authenticated %}
                                
                    <li class="nav-item">
                        <kbd class="nav-link" >Hello,{{ user.username }}.</kbd> 
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>                           
                    </li>
                                
                    {% else %}
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                        <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
                
                    {% endif %}
                                    
                </ul>                
            </div>
        </div>  
    </nav>


        <br> 
        <br> 
        <br> 

   <div class="container">
       <div class="page-header">
            {% block header %}

            {% endblock header %}
       </div>

       <div>
            {% block content %}

            {% endblock content %}
       </div>
   </div>



</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
   <div class="container" class="">
        <h4>Topic name:
            <a  class=" btn btn-info btn-lg" href="{% url 'learning_logs:topic' topic.id %}">
            {{ topic.text }}
            </a>
        </h4>
        <br>
        <br>
        <form method="POST" action="{% url 'learning_logs:edit_entry' entry.id %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save Change</button>
        </form>
   </div>
{% endblock %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}


    {% block header %}
        <h1 class="jumbotron display-2">Track your learning</h1>
    {% endblock header %}
        
   
    {% block content %}
        <h2>
            <a href="{% url 'users:signup' %}">Register an account</a> to make your own 
            Learning Log,and list the topics you are learning about.
        </h2>
        
        <h2>
            Whenever you learn something neww about a topic, make an entry summarizing what you've 
            learned.

        </h2>
    {% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}
   <div class="container" class="">
       <h2>Add a new entry:</h2>
        <h4>Topic name:
            <a  class=" btn btn-info btn-lg" href="{% url 'learning_logs:topic' topic.id %}">
            {{ topic.text }}
            </a>
        </h4>
        
        
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary btn-lg">Add</button>
        </form>
   </div>
{% endblock %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
    <h2>Add a topic:</h2>    
{% endblock header %}


{% block content %}
        <form method="POST">
            
            {% csrf_token %}
            {% bootstrap_form form %}            
            {% buttons %}
            <button type="submit" class="btn btn-primary btn-lg">Add topic</button>
            {% endbuttons %}
            
        </form>
   </div>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}


{% block header %}
    <a href="{% url 'learning_logs:topics' %}" class="btn btn-success">Go Back</a>
    <br>  <br>
    <h2>Topic:{{ topic }}</h2>
    <br>
{% endblock header %}

{% block content %}
    <a href="{% url 'learning_logs:new_entry' topic.id %}" class="btn btn-outline-danger">
        Add New Entry
    </a>
        <br>
        <br>
    <h3>Entries:</h3>



        {% for entry in entries %}
            <div class="card">
                <div class="card-header">
                    <h3>
                        {{ entry.date_added|date:'Y M d' }}
                        <small>
                            <a class="btn btn-info" href="{% url 'learning_logs:edit_entry' entry.id %}">
                                Edit entry
                            </a> 
                        </small>                       
                    </h3>
                </div>
                <div class="card-body">
                        {{ entry.text|linebreaks }}
                </div>
            </div>
        {% endfor %}                

    </ul>  
{% endblock %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}


{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}
            
    <ul>
        {% for topic in topics %}
            <li>
                <a class="topic" href="{% url 'learning_logs:topic' topic.id %}">
                    {{ topic.text }}
                </a>
            </li>
        {% empty %}
            <li>No topic has been added yet.</li>
        {% endfor %}
    </ul>
    
    <h3>
        <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-success">Add new topic</a>        
    </h3>
{% endblock %}

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
    <h2>Log into your account.</h2>
{% endblock header %}

{% block content %}
        {% if form.errors %}
        <p>Your username and password didn't match.Please try again.</p>
        {% endif %}
    
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
            <button type="submit" class="btn btn-primary">Log in</button>
             <br>
             <br>
            <a href="{% url 'users:signup' %}" class="lead">If you are not registered! Sign up first.</a>
            {% endbuttons %}            
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
        </form>
    
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn">Register</button>
            <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
        </form>
    
    </div>

{% endblock %}